# Generated by Django 5.1.1 on 2024-10-09 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dias_semana', models.CharField(max_length=200)),
                ('periodo', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ordem_totens', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Totem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(default='1100 1000', max_length=100)),
                ('cidade', models.CharField(default='N/A', max_length=100)),
                ('uf', models.CharField(default='DF', max_length=2)),
                ('geolocalizacao', models.CharField(default='1100 1000', max_length=100)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('excluido', 'Excluído')], default='ativo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Coleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('totem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.totem')),
            ],
        ),
    ]
